export default {
  products: [
    {
      _id: '1',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-01.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-02.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-03.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-04.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-05.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-06.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '7',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-07.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '8',
      name: 'Full Zip Running Shirts',
      category: 'Shirts',
      image: '/images/product-08.jpg',
      price: 60,
      brand: 'hiskywin',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
